### PR TITLE
Set host.name in Resource attributes

### LINKED ISSUE #49: Add host.name resource attribute
Add an attribute for this semantic convention in the launcher: https://github.com/open-telemetry/opentelemetry-specification/blob/b0fb442e2492a63793e32d744adbac5ff168146f/specification/resource/semantic_conventions/host.md#host

This is useful for RCA metrics ingestion, and to ensure Lightstep customers can debug issues from a specific host.

### PR DESCRIPTION
**Pull request by ocelotl**
Fixes #49

### CODE REVIEW

**Review by codeboten — CHANGES_REQUESTED** [review]
Please update the changelog and add a test to ensure a user can override the `host.name` resource attribute

**Comment by ocelotl** [comment]
> Please update the changelog and add a test to ensure a user can override the `host.name` resource attribute

Fixing...

**Comment by ocelotl** [comment]
> Please update the changelog and add a test to ensure a user can override the `host.name` resource attribute

Fixed

**Review by codeboten — APPROVED** [review]
Thanks for the updates!

**Pull request merged**
